const addBulletList = (doc, items, startY, indent = 18) => {
  if (!items || items.length === 0) {
    doc.text("None", indent, startY);
    return startY + 12;
  }

  items.forEach((item, index) => {
    const y = startY + index * 8;
    doc.text(`• ${item}`, indent, y);
  });

  return startY + items.length * 8 + 6;
};

export const generateResumeReport = async ({
  filename = "resume",
  atsScore,
  skills = [],
  strengths = [],
  suggestions = [],
  summary = "",
  jobMatchPercentage,
  matchingSkills = [],
  missingSkills = [],
  suggestedKeywords = [],
  generatedAt,
}) => {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  let y = 60;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("AI Resume Analyzer Report", margin, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${generatedAt}`, margin, y + 18);
  doc.text(`Resume File: ${filename}`, margin, y + 34);

  y = 110;
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("1. Overview", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const overviewLines = [
    `ATS Score: ${atsScore}`,
    `Job Match Percentage: ${jobMatchPercentage}%`,
  ];
  overviewLines.forEach((line, index) => {
    doc.text(line, margin, y + 18 + index * 14);
  });

  y = 155;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("2. Skills", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  y = addBulletList(doc, skills, y + 18);

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("3. Strengths", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  y = addBulletList(doc, strengths, y + 18);

  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("4. Suggestions", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  y = addBulletList(doc, suggestions, y + 18);

  if (y > pageHeight - 140) {
    doc.addPage();
    y = 60;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("5. Summary", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const summaryLines = doc.splitTextToSize(summary || "No summary available.", pageWidth - margin * 2);
  doc.text(summaryLines, margin, y + 18);

  y = y + 18 + summaryLines.length * 12 + 20;

  if (y > pageHeight - 140) {
    doc.addPage();
    y = 60;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("6. Job Match Analysis", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Matching Skills: ${matchingSkills.join(", ") || "None"}`, margin, y + 18);
  doc.text(`Missing Skills: ${missingSkills.join(", ") || "None"}`, margin, y + 34);
  doc.text(`Suggested Keywords: ${suggestedKeywords.join(", ") || "None"}`, margin, y + 50);

  doc.setFont("helvetica", "italic");
  doc.setTextColor(100);
  doc.text("Generated by AI Resume Analyzer", margin, pageHeight - 30);

  doc.save(`resume-report-${Date.now()}.pdf`);
};
